export const ROUTER_TRANSITION_ACTIONS = {
  TRANSITION_FADE: 'TRANSITION_FADE',
  TRANSITION_POP: 'TRANSITION_POP',
  TRANSITION_SLIDE_LEFT: 'TRANSITION_SLIDE_LEFT',
  TRANSITION_SLIDE_RIGHT: 'TRANSITION_SLIDE_RIGHT',
  TRANSITION_NO_ANIMATION: 'TRANSITION_NO_ANIMATION',
};

export const CATEGORY_ACTIONS = {
  ADD_CATEGORY: 'ADD_CATEGORY',
};


export const ON_DEVICE_READY = 'ON_DEVICE_READY';
export const FETCH_DB_DATA = 'FETCH_DB_DATA';
